package com.syos.domain.model;

import com.syos.domain.enums.UserRole; // Import UserRole enum
import java.util.Objects;

public class Employee {
    private int employeeId;
    private String username;
    private String passwordHash;
    private String fullName;
    private UserRole role; // FIX: Changed from String to UserRole

    public Employee() { // No-arg constructor for frameworks
    }

    // Constructor for new employees (ID generated by DB)
    public Employee(String username, String passwordHash, String fullName, UserRole role) { // FIX: UserRole for role
        if (username == null || username.trim().isEmpty()) throw new IllegalArgumentException("Username cannot be null or empty.");
        if (passwordHash == null || passwordHash.trim().isEmpty()) throw new IllegalArgumentException("Password hash cannot be null or empty.");
        if (role == null) throw new IllegalArgumentException("Role cannot be null.");

        this.username = username;
        this.passwordHash = passwordHash;
        this.fullName = fullName;
        this.role = role;
    }

    // Full constructor for loading from DB
    public Employee(int employeeId, String username, String passwordHash, String fullName, UserRole role) { // FIX: UserRole for role
        this(username, passwordHash, fullName, role); // Call validating constructor
        this.employeeId = employeeId;
    }

    // Getters
    public int getEmployeeId() { return employeeId; }
    public String getUsername() { return username; }
    public String getPasswordHash() { return passwordHash; }
    public String getFullName() { return fullName; }
    public UserRole getRole() { return role; } // FIX: Return UserRole

    // Setters
    public void setEmployeeId(int employeeId) { this.employeeId = employeeId; }
    public void setUsername(String username) {
        if (username == null || username.trim().isEmpty()) throw new IllegalArgumentException("Username cannot be null or empty.");
        this.username = username;
    }
    public void setPasswordHash(String passwordHash) {
        if (passwordHash == null || passwordHash.trim().isEmpty()) throw new IllegalArgumentException("Password hash cannot be null or empty.");
        this.passwordHash = passwordHash;
    }
    public void setFullName(String fullName) { this.fullName = fullName; }
    public void setRole(UserRole role) { // FIX: Accept UserRole
        if (role == null) throw new IllegalArgumentException("Role cannot be null.");
        this.role = role;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Employee employee = (Employee) o;
        if (employeeId != 0 && employee.employeeId != 0) return employeeId == employee.employeeId;
        return Objects.equals(username, employee.username); // Fallback for new employees not yet persisted
    }

    @Override
    public int hashCode() {
        if (employeeId != 0) return Objects.hash(employeeId);
        return Objects.hash(username);
    }

    @Override
    public String toString() {
        return "Employee{" +
                "employeeId=" + employeeId +
                ", username='" + username + '\'' +
                ", fullName='" + fullName + '\'' +
                ", role=" + role +
                '}';
    }
}
